name: Deploy to SFTP

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to SFTP
        uses: airsend-io/sftp-action@master
        with:
          host: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          localDir: './'
          remoteDir: '/home/graydori/shan.naziripour.com/'

