name: Deploy to SFTP

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to SFTP
        uses: milanmk/actions-file-deployer@1.18
        with:
          remote-host: ${{ secrets.SFTP_SERVER }}
          remote-user: ${{ secrets.SFTP_USERNAME }}
          remote-password: ${{ secrets.SFTP_PASSWORD }}
          local-path: "./"
          remote-path: "/home/graydori/shan.naziripour.com/"
          sync: "full"
          debug: true
